#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m'

colors=($RED $GREEN $YELLOW $BLUE $PURPLE $CYAN)

output=$(go run main.go "$1" "$2")
index=$(( RANDOM % ${#colors[@]} ))
color=${colors[$index]}

printf "${color}${output}${NC}\n"

